INSERT INTO `{{prefix}}schools` (id, school_name)
VALUES
    (1, 'Norra Gymnasiet'),
    (2, 'Södra Gymnasiet')
ON DUPLICATE KEY UPDATE
    school_name = VALUES(school_name);

INSERT INTO `{{prefix}}categories` (id, category_name)
VALUES
    (1, 'Svenska'),
    (2, 'Fysik'),
    (7, 'Biologi'),
    (8, 'Kemi'),
    (9, 'Teknik'),
    (10, 'Samhällskunskap'),
    (11, 'Historia'),
    (12, 'Programmering'),
    (14, 'Ekonomi'),
    (15, 'Annat')
ON DUPLICATE KEY UPDATE
    category_name = VALUES(category_name);

INSERT INTO `{{prefix}}users` (username, email, password_hash, full_name, role, school_id, approval_status, reviewed_at)
VALUES
    ('elev', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Exempel Elev', 'student', 1, 'approved', NOW()),
    ('larare', NULL, '$2y$12$sb.qv0WG12fcpTrumaxxk.NFPPlt5OQuObfqJzB2QspLyYOvnRymW', 'Exempel Lärare', 'teacher', 1, 'approved', NOW()),
    ('elev1', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Maja Andersson', 'student', 1, 'approved', NOW()),
    ('elev2', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Leo Karlsson', 'student', 1, 'approved', NOW()),
    ('elev3', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Busig Elev', 'student', 1, 'approved', NOW()),
    ('elev4', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Sara Nguyen', 'student', 1, 'approved', NOW()),
    ('elev5', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Omar Hassan', 'student', 1, 'approved', NOW()),
    ('elev6', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Elin Berg', 'student', 1, 'approved', NOW()),
    ('elev7', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Nora Lind', 'student', 2, 'approved', NOW()),
    ('elev8', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Adam Svensson', 'student', 2, 'approved', NOW()),
    ('elev9', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Lina Persson', 'student', 2, 'approved', NOW()),
    ('larare_sodra', NULL, '$2y$12$sb.qv0WG12fcpTrumaxxk.NFPPlt5OQuObfqJzB2QspLyYOvnRymW', 'Södra Handledare', 'teacher', 2, 'approved', NOW())
ON DUPLICATE KEY UPDATE
    email = VALUES(email),
    full_name = VALUES(full_name),
    role = VALUES(role),
    school_id = VALUES(school_id),
    approval_status = VALUES(approval_status);

INSERT INTO `{{prefix}}projects`
    (user_id, school_id, category_id, title, subtitle, supervisor, supervisor_user_id, abstract_text, summary_text, is_public, is_submitted, is_approved, submitted_at, approved_at, approved_by)
VALUES
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev'),
        1,
        2,
        'Hållbar energianvändning i skolmiljö',
        'En fallstudie av elanvändning',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'The study shows that clearer visualization of consumption and changed routines can reduce unnecessary electricity use.',
        'Studien visar att tydligare visualisering av förbrukning och ändrade rutiner kan minska onödig elanvändning.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev1'),
        1,
        7,
        'Mikroplaster i dagvatten nära skolområdet',
        'Provtagning och analys av lokala vattenflöden',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'The results show that particle levels vary clearly between sampling sites and that surfaces close to traffic produce higher values. The project discusses simple measures such as filters, better cleaning and more deliberate stormwater management.',
        'Resultaten visar att mängden partiklar varierar tydligt mellan provplatserna och att trafiknära ytor ger högre värden. Arbetet diskuterar enkla åtgärder som filter, bättre städning och mer genomtänkt dagvattenhantering.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev2'),
        1,
        12,
        'En webbapp för planering av gymnasiestudier',
        'Prototyp med påminnelser och prioritering',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'The prototype shows that clear views for week, subject and deadline make planning easier to understand. Test users felt that reminders and fewer choices per screen made the tool easier to use.',
        'Prototypen visar att tydliga vyer för vecka, ämne och deadline gör planeringen mer överskådlig. Testpersoner upplevde att påminnelser och färre val per skärm gjorde verktyget lättare att använda.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev3'),
        1,
        15,
        'Varför chips är bättre än matte',
        'En helt ovetenskaplig undersökning',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'The conclusion is that crisps feel more fun than mathematics, but the reasoning lacks delimitation, source criticism and analysis. The project is therefore submitted as an example of unserious material that needs feedback before publication.',
        'Slutsatsen är att chips känns roligare än matematik, men resonemanget saknar avgränsning, källkritik och analys. Arbetet är därför inlämnat som exempel på ett oseriöst underlag som behöver återkoppling innan publicering.',
        1,
        1,
        0,
        NOW(),
        NULL,
        NULL
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev4'),
        1,
        11,
        'Industrialiseringens spår i den egna kommunen',
        'En lokalhistorisk studie med arkivmaterial',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'The study shows that the railway route and the establishment of smaller workshops changed both the labour market and local settlement patterns. The project connects local changes to broader Swedish industrialization processes.',
        'Studien visar att järnvägens dragning och etableringen av mindre verkstäder förändrade både arbetsmarknad och bebyggelse. Arbetet kopplar lokala förändringar till större svenska industrialiseringsprocesser.',
        0,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev5'),
        1,
        14,
        'Unga vuxnas privatekonomi efter studenten',
        'Budget, konsumtion och sparande',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'The results show that many young adults underestimate recurring small expenses and lack a margin for unexpected costs. The project proposes a simple budget model that can be used in personal finance education.',
        'Resultaten visar att många underskattar återkommande småkostnader och saknar marginal för oförutsedda utgifter. Arbetet föreslår en enkel budgetmodell som kan användas i undervisning om privatekonomi.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev6'),
        1,
        9,
        '3D-printade reservdelar i skolmiljö',
        'Hållfasthet, kostnad och användbarhet',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'The tests show that 3D printing can work for some low-load parts, but that material choice and print orientation are decisive. The project also highlights documentation and safety limits as important before the parts are used.',
        'Tester visar att 3D-printning kan fungera för vissa låg belastade detaljer, men att materialval och utskriftsriktning är avgörande. Arbetet lyfter även dokumentation och säkerhetsgränser som viktiga innan delarna används.',
        0,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev7'),
        2,
        8,
        'C-vitaminhalt i fruktjuice över tid',
        'En jämförelse mellan färskpressad och pastöriserad juice',
        'Södra Handledare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra'),
        'The results show that storage temperature and exposure to air clearly affect the vitamin content. Freshly pressed juice had the highest initial value but lost vitamin C faster than pasteurized juice at room temperature.',
        'Resultaten visar att förvaringstemperatur och exponering för luft påverkar halten tydligt. Färskpressad juice hade högst startvärde men tappade snabbare än pastöriserad juice vid rumstemperatur.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev8'),
        2,
        10,
        'Ungas nyhetsvanor och källkritik',
        'Sociala medier som första nyhetskälla',
        'Södra Handledare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra'),
        'The study shows that many students quickly check sender and date, but less often follow links to the original source. The project proposes clearer teaching about reverse image search, primary sources and the influence of algorithms.',
        'Studien visar att många elever snabbt kontrollerar avsändare och datum, men mer sällan följer länkar till ursprungskällan. Arbetet föreslår tydligare undervisning kring bildsökning, primärkällor och algoritmers påverkan.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev9'),
        2,
        1,
        'Språkbruk i svenska samtalspoddar',
        'Informellt tal, kodväxling och publiknärhet',
        'Södra Handledare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra'),
        'The analysis shows that spoken-language markers, English expressions and direct address are used to create pace and a sense of community. The project discusses how the format influences norms for public language.',
        'Analysen visar att talspråkliga markörer, engelska uttryck och direkt tilltal används för att skapa tempo och gemenskap. Arbetet diskuterar hur formatet påverkar normer för offentligt språk.',
        0,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra')
    )
ON DUPLICATE KEY UPDATE
    school_id = VALUES(school_id),
    category_id = VALUES(category_id),
    title = VALUES(title),
    subtitle = VALUES(subtitle),
    supervisor = VALUES(supervisor),
    supervisor_user_id = VALUES(supervisor_user_id),
    abstract_text = VALUES(abstract_text),
    summary_text = VALUES(summary_text),
    is_public = VALUES(is_public),
    is_submitted = VALUES(is_submitted),
    is_approved = VALUES(is_approved),
    submitted_at = VALUES(submitted_at),
    approved_at = VALUES(approved_at),
    approved_by = VALUES(approved_by);
