INSERT INTO `{{prefix}}schools` (id, school_name)
VALUES
    (1, 'Norra Gymnasiet'),
    (2, 'Södra Gymnasiet')
ON DUPLICATE KEY UPDATE
    school_name = VALUES(school_name);

INSERT INTO `{{prefix}}categories` (id, category_name)
VALUES
    (1, 'Svenska'),
    (2, 'Fysik'),
    (7, 'Biologi'),
    (8, 'Kemi'),
    (9, 'Teknik'),
    (10, 'Samhällskunskap'),
    (11, 'Historia'),
    (12, 'Programmering'),
    (14, 'Ekonomi'),
    (15, 'Annat')
ON DUPLICATE KEY UPDATE
    category_name = VALUES(category_name);

INSERT INTO `{{prefix}}users` (username, email, password_hash, full_name, role, school_id, approval_status, reviewed_at)
VALUES
    ('elev', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Exempel Elev', 'student', 1, 'approved', NOW()),
    ('larare', NULL, '$2y$12$sb.qv0WG12fcpTrumaxxk.NFPPlt5OQuObfqJzB2QspLyYOvnRymW', 'Exempel Lärare', 'teacher', 1, 'approved', NOW()),
    ('elev1', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Maja Andersson', 'student', 1, 'approved', NOW()),
    ('elev2', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Leo Karlsson', 'student', 1, 'approved', NOW()),
    ('elev3', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Busig Elev', 'student', 1, 'approved', NOW()),
    ('elev4', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Sara Nguyen', 'student', 1, 'approved', NOW()),
    ('elev5', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Omar Hassan', 'student', 1, 'approved', NOW()),
    ('elev6', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Elin Berg', 'student', 1, 'approved', NOW()),
    ('elev7', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Nora Lind', 'student', 2, 'approved', NOW()),
    ('elev8', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Adam Svensson', 'student', 2, 'approved', NOW()),
    ('elev9', NULL, '$2y$12$0.DUDRZdUGfuDFBT2c9OhueAJTGkWIFbd.IKyXI5kiGIaYseULKUe', 'Lina Persson', 'student', 2, 'approved', NOW()),
    ('larare_sodra', NULL, '$2y$12$sb.qv0WG12fcpTrumaxxk.NFPPlt5OQuObfqJzB2QspLyYOvnRymW', 'Södra Handledare', 'teacher', 2, 'approved', NOW())
ON DUPLICATE KEY UPDATE
    email = VALUES(email),
    full_name = VALUES(full_name),
    role = VALUES(role),
    school_id = VALUES(school_id),
    approval_status = VALUES(approval_status);

INSERT INTO `{{prefix}}projects`
    (user_id, school_id, category_id, title, subtitle, supervisor, supervisor_user_id, abstract_text, summary_text, is_public, is_submitted, is_approved, submitted_at, approved_at, approved_by)
VALUES
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev'),
        1,
        2,
        'Hållbar energianvändning i skolmiljö',
        'En fallstudie av elanvändning',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'Arbetet undersöker hur en gymnasieskola kan kartlägga och minska sin energianvändning med enkla mätmetoder.',
        'Studien visar att tydligare visualisering av förbrukning och ändrade rutiner kan minska onödig elanvändning.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev1'),
        1,
        7,
        'Mikroplaster i dagvatten nära skolområdet',
        'Provtagning och analys av lokala vattenflöden',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'Arbetet undersöker förekomsten av mikroplaster i dagvatten från hårdgjorda ytor nära skolan. Prover samlas in efter regn och jämförs med kontrollprover från en närliggande parkmiljö.',
        'Resultaten visar att mängden partiklar varierar tydligt mellan provplatserna och att trafiknära ytor ger högre värden. Arbetet diskuterar enkla åtgärder som filter, bättre städning och mer genomtänkt dagvattenhantering.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev2'),
        1,
        12,
        'En webbapp för planering av gymnasiestudier',
        'Prototyp med påminnelser och prioritering',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'Arbetet beskriver utvecklingen av en enkel webbapplikation där elever kan planera prov, deadlines och självstudier. Fokus ligger på användbarhet, datamodell och hur prioriteringar kan visas utan att gränssnittet blir rörigt.',
        'Prototypen visar att tydliga vyer för vecka, ämne och deadline gör planeringen mer överskådlig. Testpersoner upplevde att påminnelser och färre val per skärm gjorde verktyget lättare att använda.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev3'),
        1,
        15,
        'Varför chips är bättre än matte',
        'En helt ovetenskaplig undersökning',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'Arbetet bygger främst på elevens egna åsikter, en mycket liten omröstning i klassrummet och flera påståenden som inte följs upp med källor. Metoden är otydlig och frågeställningen går inte att pröva på ett seriöst sätt.',
        'Slutsatsen är att chips känns roligare än matematik, men resonemanget saknar avgränsning, källkritik och analys. Arbetet är därför inlämnat som exempel på ett oseriöst underlag som behöver återkoppling innan publicering.',
        1,
        1,
        0,
        NOW(),
        NULL,
        NULL
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev4'),
        1,
        11,
        'Industrialiseringens spår i den egna kommunen',
        'En lokalhistorisk studie med arkivmaterial',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'Arbetet undersöker hur industrialiseringen påverkade arbete, boende och transporter i kommunen. Källmaterialet består av äldre kartor, kommunala protokoll, fotografier och intervjuer med lokalhistoriskt kunniga personer.',
        'Studien visar att järnvägens dragning och etableringen av mindre verkstäder förändrade både arbetsmarknad och bebyggelse. Arbetet kopplar lokala förändringar till större svenska industrialiseringsprocesser.',
        0,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev5'),
        1,
        14,
        'Unga vuxnas privatekonomi efter studenten',
        'Budget, konsumtion och sparande',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'Arbetet analyserar hur unga vuxna planerar sin ekonomi under det första året efter gymnasiet. En enkät kombineras med en jämförelse av typiska kostnader för boende, mat, resor och fritid.',
        'Resultaten visar att många underskattar återkommande småkostnader och saknar marginal för oförutsedda utgifter. Arbetet föreslår en enkel budgetmodell som kan användas i undervisning om privatekonomi.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev6'),
        1,
        9,
        '3D-printade reservdelar i skolmiljö',
        'Hållfasthet, kostnad och användbarhet',
        'Exempel Lärare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare'),
        'Arbetet testar om enklare reservdelar till skolans utrustning kan modelleras och 3D-printas på ett tillförlitligt sätt. Olika material och infill-nivåer jämförs genom praktiska belastningstester.',
        'Tester visar att 3D-printning kan fungera för vissa låg belastade detaljer, men att materialval och utskriftsriktning är avgörande. Arbetet lyfter även dokumentation och säkerhetsgränser som viktiga innan delarna används.',
        0,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev7'),
        2,
        8,
        'C-vitaminhalt i fruktjuice över tid',
        'En jämförelse mellan färskpressad och pastöriserad juice',
        'Södra Handledare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra'),
        'Arbetet undersöker hur C-vitaminhalten förändras när olika typer av juice förvaras i kylskåp respektive rumstemperatur. Jodometrisk titrering används för att jämföra prover vid flera tidpunkter.',
        'Resultaten visar att förvaringstemperatur och exponering för luft påverkar halten tydligt. Färskpressad juice hade högst startvärde men tappade snabbare än pastöriserad juice vid rumstemperatur.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev8'),
        2,
        10,
        'Ungas nyhetsvanor och källkritik',
        'Sociala medier som första nyhetskälla',
        'Södra Handledare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra'),
        'Arbetet undersöker hur gymnasieelever värderar nyheter från sociala medier jämfört med etablerade nyhetsredaktioner. En enkät kombineras med korta intervjuer om källkritiska strategier.',
        'Studien visar att många elever snabbt kontrollerar avsändare och datum, men mer sällan följer länkar till ursprungskällan. Arbetet föreslår tydligare undervisning kring bildsökning, primärkällor och algoritmers påverkan.',
        1,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra')
    ),
    (
        (SELECT id FROM `{{prefix}}users` WHERE username = 'elev9'),
        2,
        1,
        'Språkbruk i svenska samtalspoddar',
        'Informellt tal, kodväxling och publiknärhet',
        'Södra Handledare',
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra'),
        'Arbetet analyserar hur programledare i svenska samtalspoddar använder informellt språk för att skapa närhet till lyssnaren. Materialet består av transkriberade utdrag från tre poddar med olika målgrupper.',
        'Analysen visar att talspråkliga markörer, engelska uttryck och direkt tilltal används för att skapa tempo och gemenskap. Arbetet diskuterar hur formatet påverkar normer för offentligt språk.',
        0,
        1,
        1,
        NOW(),
        NOW(),
        (SELECT id FROM `{{prefix}}users` WHERE username = 'larare_sodra')
    )
ON DUPLICATE KEY UPDATE
    school_id = VALUES(school_id),
    category_id = VALUES(category_id),
    title = VALUES(title),
    subtitle = VALUES(subtitle),
    supervisor = VALUES(supervisor),
    supervisor_user_id = VALUES(supervisor_user_id),
    abstract_text = VALUES(abstract_text),
    summary_text = VALUES(summary_text),
    is_public = VALUES(is_public),
    is_submitted = VALUES(is_submitted),
    is_approved = VALUES(is_approved),
    submitted_at = VALUES(submitted_at),
    approved_at = VALUES(approved_at),
    approved_by = VALUES(approved_by);
